### PR TITLE
Config Improvements

### PR DESCRIPTION
**Pull request by T14D3**
See commits

Added Config options, added config auto updater

### CODE REVIEW

**Review by Ghost-chu — APPROVED** [review]

**Comment by Ghost-chu** [comment]
Very valuable PR, thanks for your contribution! :)

**Comment by T14D3** [comment]
That was fast lol

**Comment by Ghost-chu** [comment]
Do you have a Modrinth account? I'd like to add you to Contributors.

**Comment by Ghost-chu** [comment]
Resolved #3

**Comment by T14D3** [comment]
> Do you have a Modrinth account? I'd like to add you to Contributors.

Now I do lol, same name as here (id p30tYe5W)

**Comment by Ghost-chu** [comment]
I've granted you (almost all) access to the Modrinth project and the Github repository, so you can make changes or release new versions at will (including Modrinth monetization).
Thanks to Paper's performance optimizations, I'm glad I can be less concerned about Entity performance issues, and this project is in a minimal maintenance state for me.
It's nice to see that the project is still helping other peoples.

**Comment by T14D3** [comment]
Thanks, will update the modrinth page with new release and changed config example in a bit^^

**Pull request merged**
