### PR TITLE
Reload command and PAPI Expansion

### PR DESCRIPTION
**Pull request by T14D3**
/chunkheat reload

%chunkheat_value%

### CODE REVIEW

**Comment by Ghost-chu** [comment]
LGTM

**Comment by T14D3** [comment]
_Is this gonna get merged at all? :p_

**Comment by Ghost-chu** [comment]
sry, I forget this PR and LGTM (again).

**Comment by T14D3** [comment]
Don't worry about it, was gonna make a new pr earlier and saw this one still open so was wondering if it was even active anymore, but glad to see it is :)

**Pull request merged**
